---
# Description
- name: Create MySQL by Ansible
  hosts: db_and_web_server1, db_and_web_server2
  gather_facts: true
  become: true                  # Become root user
  # vars:
  #   db_name: employee_db
  #   db_user: db_user
  #   db_password: P@ssw0rd

  tasks:
    - name: Install all required dependencies
      apt: 
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python-setuptools
        - build-essential
        - python3-mysqldb
        - pip
        - telnetd
        - net-tools
        - firewalld
        - tree
    - include: tasks/deploy_db.yml
    - include: tasks/deploy_web.yml
...
