    - name: Install all required dependencies
      apt: 
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python-setuptools
        - build-essential
        - python3-mysqldb
        - pip
        - telnetd
        - net-tools
        - firewalld
        - tree