    - name: Permit traffit in default zone on port 3306/tcp
      ansible.posix.firewalld:
        port: 3306/tcp
        permanent: true
        zone: public
        state: enabled

    - name: Restart Firewall Service
      ansible.builtin.service:
        name: firewalld
        state: restarted

    - name: Install MySQL database
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - mysql-server
        - mysql-client

    - name: Create database and database users
      community.mysql.mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ db_name }}"
        state: present

    - name: Ensure MySQL is configured to bind to the specified address and port
      community.general.ini_file:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        section: mysqld
        option: "{{ item.option }}"
        value: "{{ item.value }}"            
        state: present
      with_items:
        - { option: bind-address, value: 0.0.0.0 }          # Allow all hosts to connect to this port, default is 127.0.0.1 (only allow local host to connect)
        - { option: mysqlx-bind-address, value: 0.0.0.0 }

    - name: Create database user
      community.mysql.mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock      # Allow login mysql db via socket
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: '*.*:ALL,GRANT'                               #<database.*>
        host: '%'                                           # Allow all host to connect to mysql db
        state: present

    - name: Restart MySQL DB                                # To apply all the configuration
      ansible.builtin.service:
        name: mysql
        state: restarted